### PR TITLE
remove single bundle

### PR DESCRIPTION
**Pull request by alessandroabba**
instead of using reset(), it would be nice to be able to remove only a single bundle and its dependencies from cached ones.

### CODE REVIEW

**Comment by amorey** [comment]
This appears to be a pull request from one branch of `loadjs` into another. Are you trying to create a PR or an Issue?

**Comment by alessandroabba** [comment]
PR

**Comment by amorey** [comment]
Hmm... which file changed? The description of the PR says it's a merge from `muicss/loadjs:W1zzardTPU_master` into `muicss/loadjs:master`. I looked at the file changes and they appear to already be in the master.

**Comment by alessandroabba** [comment]
I'm doing it in my repo, sorry for the mistake, it's my first PR. I'll make the pull again from the rigth branch once done.

**Comment by amorey** [comment]
Ok, thanks. Can you describe the use case for removing single bundles?

**Pull request closed without merging**
