### PR TITLE
Adding support for beforeload-blocked scripts in Safari

### PR DESCRIPTION
**Pull request by codeburke**
This PR is addressing an issue with Safari and ad blockers. Some ad blockers (example: Ghostery) block requests in such a way that there is no "onerror" or "onload" callbacks ever sent back to the application. This can cause indefinite hangs when a blocked script is listed as a dependency. The solution should be to report the script as missing and let the application deal with it however it wants.

You can see this in action by doing the following in Safari:
1. Install Ghostery extension
2. Go to https://jsfiddle.net/aofscrtz/2/. (notice it should say "success!", if you don't have other ad blockers already)
3. Click on the Ghostery extension and disable "Google Adservices".
4. Reload the page
5. Notice that there is no message of success of missing.

I've tested this in Chrome 50, FF 44 and Safari 9.0.2 on OS X 10.11.2. I'd love some additional testing on Windows machines and browsers.

### CODE REVIEW

**Comment by amorey** [comment]
Awesome! This is very useful. I can test it out and merge it tonight.

**Comment by codeburke** [comment]
Awesome. I'd love to get this into a release.

**Comment by amorey** [comment]
It works great! I shaved off 10 more bytes from your fork and issued a pull request:
https://github.com/codeburke/loadjs/pull/1

If that looks good can you update this PR and I'll create a new release?

**Comment by codeburke** [comment]
I added one comment to that PR before I update this one. If you could take a look when you get a few minutes.

**Comment by amorey** [comment]
@codeburke Thanks again for working on this. I merged your code into the master and released a new version (v1.0.4). Let me know if I can add you to the contributors list (or add yourself in a PR!):
https://github.com/muicss/loadjs/blob/master/AUTHORS.txt

**Pull request merged**
